T_HH                            '<?hh'                          0   0, 4
T_LVAR                          '$xhp'                          2   6, 10
T_EQ                            '='                             2   11, 12
T_XHP_NAME                      '<foo'                          2   13, 17
T_XHP_COMMENT                   ' </foo> '                      2   17, 34
T_XHP_CLOSING                   'foo'                           2   36, 41
T_SC                            ';'                             2   41, 42
T_LVAR                          '$xhp'                          3   43, 47
T_EQ                            '='                             3   48, 49
T_XHP_NAME                      '<bar'                          3   50, 54
T_XHP_COMMENT                   '
    </bar>
'                  5   54, 75
T_XHP_CLOSING                   'bar'                           5   77, 82
T_SC                            ';'                             5   82, 83
